FROM node:18-alpine

WORKDIR /app

# Installation des outils de développement
RUN apk add --no-cache bash git curl python3

# Copie et installation des dépendances
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

# Expose des ports pour l'API et le débogueur
EXPOSE 5000 9229

CMD ["npm", "run", "dev"]